#
#
#    ADOBE CONFIDENTIAL
#    ___________________
#
#    Copyright 2020 Adobe Systems Incorporated
#    All Rights Reserved.
#
#    NOTICE:  All information contained herein is, and remains
#    the property of Adobe Systems Incorporated and its suppliers,
#    if any.  The intellectual and technical concepts contained
#    herein are proprietary to Adobe Systems Incorporated and its
#    suppliers and are protected by all applicable intellectual property
#    laws, including trade secret and copyright laws.
#    Dissemination of this information or reproduction of this material
#    is strictly forbidden unless prior written permission is obtained
#    from Adobe Systems Incorporated.
#

#
# This is the theme configuration
# Allowed configuration in a theme is (currently):
# params (global and per language)
# menu (global and per language)
# outputformats and mediatypes

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
fuseSearch = true
