#
#
#    ADOBE CONFIDENTIAL
#    ___________________
#
#    Copyright 2020 Adobe Systems Incorporated
#    All Rights Reserved.
#
#    NOTICE:  All information contained herein is, and remains
#    the property of Adobe Systems Incorporated and its suppliers,
#    if any.  The intellectual and technical concepts contained
#    herein are proprietary to Adobe Systems Incorporated and its
#    suppliers and are protected by all applicable intellectual property
#    laws, including trade secret and copyright laws.
#    Dissemination of this information or reproduction of this material
#    is strictly forbidden unless prior written permission is obtained
#    from Adobe Systems Incorporated.
#

name = "Adobe Spectrum Hugo Theme"
license = "MIT"
licenselink = "https://github.com/adobe/hugo-spectrum/blob/master/LICENSE"
description = "Hugo theme using Adobe Coral Spectrum styling"
homepage = "https://github.com/adobe/hugo-spectrum"
tags = ["documentation"]
features = []
min_version = "0.62.2"

[author]
  name = "Adobe"
  homepage = "https://github.com/adobe"
