#
#
#    ADOBE CONFIDENTIAL
#    ___________________
#
#    Copyright 2020 Adobe Systems Incorporated
#    All Rights Reserved.
#
#    NOTICE:  All information contained herein is, and remains
#    the property of Adobe Systems Incorporated and its suppliers,
#    if any.  The intellectual and technical concepts contained
#    herein are proprietary to Adobe Systems Incorporated and its
#    suppliers and are protected by all applicable intellectual property
#    laws, including trade secret and copyright laws.
#    Dissemination of this information or reproduction of this material
#    is strictly forbidden unless prior written permission is obtained
#    from Adobe Systems Incorporated.
#

baseURL: "https://git.corp.adobe.com/pages/reef/hugo-spectrum"
title: Adobe Spectrum Hugo Theme
params:
  ui:
    sidebar_menu_compact: true
  fuseSearch: true
  github_repo: "https://git.corp.adobe.com/pages/reef/hugo-spectrum"
  github_subdir: "content"
outputs:
  home:
    - json
    - html
theme: "hugo-spectrum"
enableGitInfo: true
canonifyURLs: true
metaDataFormat: "yaml"
publishDir: build
contentDir: "content"
disableKinds:
 - "RSS"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    title: Adobe Spectrum Hugo Demo

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false  
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "github"
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
module:
  mounts:
  - source: content
    target: content
